version: 2

defaults: &defaults
  docker:
    - image: circleci/node:12
  working_directory: ~/atlas

jobs:
  install:
    <<: *defaults
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install --ignore-optional --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  unittest:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .

      - run:
          name: Run unit tests
          command: yarn test:unit

  integrationtest:
    docker:
      - image: circleci/node:10.14-browsers
        environment:
          TERM: xterm
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run integration tests
          command: |
            yarn test:e2e:ci

  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint files
          command: yarn format

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  typecheck:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Typecheck
          command: yarn tsc

  storybook:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build storybook
          command: yarn build:storybook

workflows:
  version: 2
  test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - typecheck:
          requires:
            - install
      - build:
          requires:
            - lint
            - typecheck
      - storybook:
          requires:
            - lint
            - typecheck
      - unittest:
          requires:
            - typecheck
      - integrationtest:
          requires:
            - build
