# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  install:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: yarn install && yarn add -g typescript
  unittest:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - run:
          name: Run unit tests
          command: yarn test:unit
  integrationtest:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Run integration tests
          command: yarn test:e2e:ci
  lint:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Lint files
          command: yarn format
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Build
          command: yarn build
  typecheck:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Typecheck
          command: yarn tsc
  storybook:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Build storybook
          command: yarn build:storybook

workflows:
  version: 2
  test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - typecheck:
          requires:
            - install
      - build:
          requires:
            - lint
            - typecheck
      - storybook:
          requires:
            - lint
            - typecheck
      - unittest:
          requires:
            - build
      - integrationtest:
          requires:
            - build
