name: CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: CI
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn format

      - name: Typecheck
        run: yarn tsc

      - name: Build
        run: yarn build

      - name: Unittests
        run: yarn test:unit

      - name: Integration tests
        uses: cypress-io/github-action@v1.16.1
        with:
          build: npm run build
          start: npm run serve
          wait-on: http://localhost:5000

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: chronark/atlas
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
