name: CI

on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: CI on ${{matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ matrix.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ matrix.os }}-yarn-

      - name: Installing dependencies
        run: yarn install

      - name: Linting
        run: yarn format

      - name: Typechecking
        run: yarn tsc

      - name: Building package
        run: yarn build

      - name: Unittests
        run: yarn test:unit

      - name: Integration tests
        run: yarn test:e2e:ci
