name: CI

on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: CI on ${{matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Installing dependencies
        run: yarn install

      - name: Linting
        run: yarn format

      - name: Typechecking
        run: yarn tsc

      - name: Building package
        run: yarn build

      - name: Unittests
        run: yarn test:unit

      - name: Integration tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome __tests__/e2e/*.test.ts"
