name: CI

on: [push]
jobs:
  integration:
    runs-on: ubuntu-latest
    name: integration
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn format

      - name: Typecheck
        run: yarn tsc

      - name: Unittests
        run: yarn test:unit

      - name: Integration tests
        uses: cypress-io/github-action@v1.16.1
        with:
          build: ./node_modules/.bin/webpack --mode=production
          start: npm run serve
          wait-on: http://localhost:5000

  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: ./node_modules/.bin/webpack --mode=production

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: chronark/atlas/latest
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
