name: CI

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 10.x, 12.x ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn format
      - run: yarn tsc
      - run: yarn build
      - run: yarn storybook
      - run: yarn test:unit
      - run: yarn test:e2e
