name: CI

on: [push, pull_request]

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn install
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v1
      - run: yarn format
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    # This job will only run if both `test` and `lint` jobs run successfully.
    needs: install
    steps:
      - uses: actions/checkout@v1
      - run: yarn tsc
  build:
    name: Build
    runs-on: ubuntu-latest
    # This job will only run if both `test` and `lint` jobs run successfully.
    needs: [lint, typecheck]
    steps:
      - uses: actions/checkout@v1
      - run: yarn build
  storybook:
    name: Storybook
    runs-on: ubuntu-latest
    # This job will only run if both `test` and `lint` jobs run successfully.
    needs: [lint, typecheck]
    steps:
      - uses: actions/checkout@v1
      - run: yarn storybook
  unittest:
    name: Unittest
    runs-on: ubuntu-latest
    # This job will only run if both `test` and `lint` jobs run successfully.
    needs: typecheck
    steps:
      - uses: actions/checkout@v1
      - run: yarn test:unit
  e2etests:
    name: End to end tests
    runs-on: ubuntu-latest
    # This job will only run if both `test` and `lint` jobs run successfully.
    needs: build
    steps:
      - uses: actions/checkout@v1
      - run: yarn test:e2e
